import time
import tos
import sys
time.sleep(0.3)
print("Compatible TrashOS version detected:", tos.version)
print("Compatible devices:")
print("iPhone 3GS-iPhone 6")
print("iPad Mini 2-iPad Air 4")
print("All T2 Macs")
print("--------------------")
time.sleep(0.5)
print("Scanning LAN..")
time.sleep(0.8)
print("Detected jailbreakable iDevice on LAN")
print("Device is iPhone 5S")
confirm = input("Are you sure you want to jailbreak? (Y/N) ").upper()
if confirm == "Y":
    print("Gaining connection..")
    time.sleep(1)
    print("Sending payload")
    time.sleep(0.6)
    print("SSH init")
    time.sleep(1)
    print("Heap feng Sha...")
    time.sleep(0.8)
    print("Heap spraying...")
    time.sleep(0.9)
    print("Payload running..")
    time.sleep(2)
    print("Jailbreak done! Please restart your iDevice.")
else:
    print("Invalid input")
    sys.exit()